export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const GET_EVENT_DETAIL_REQUEST = "GET_EVENT_DETAIL_REQUEST";
export const GET_EVENT_DETAIL_SUCCES = "GET_EVENT_DETAIL_SUCCES";
export const GET_EVENT_DETAIL_FAILED = "GET_EVENT_DETAIL_FAILED";

export const GET_ATTEND_EVENT_REQUEST = "GET_ATTEND_EVENT_REQUEST";
export const GET_ATTEND_EVENT_SUCCES = "GET_ATTEND_EVENT_SUCCES";
export const GET_ATTEND_EVENT_FAILED = "GET_ATTEND_EVENT_FAILED";

export const GET_EVENTS_REQUEST = "GET_EVENTS_REQUEST";
export const GET_EVENTS_SUCCES = "GET_EVENTS_SUCCES";
export const GET_EVENTS_FAILED = "GET_EVENTS_FAILED";

export const GET_COMMENT_REQUEST = "GET_COMMENT_REQUEST";
export const GET_COMMENT_SUCCES = "GET_COMMENT_SUCCES";
export const GET_COMMENT_FAILED = "GET_COMMENT_FAILED";

export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST";
export const POST_COMMENT_SUCCES = "POST_COMMENT_SUCCES";
export const POST_COMMENT_FAILED = "POST_COMMENT_FAILED";

export const SEARCH_EVENT_CATEGORY = "SEARCH_EVENT_CATEGORY";
export const SEARCH_EVENTS = "SEARCH_EVENTS";
